# Generated by Django 4.0.3 on 2024-07-05 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('date', models.DateTimeField(verbose_name='Dia e hora do compromisso')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('description', models.TextField(blank=True, verbose_name='Informações do compromisso')),
                ('psycologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.psychologistmodel')),
            ],
        ),
    ]
