# Generated by Django 4.0.3 on 2024-06-27 22:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('date', models.DateTimeField(verbose_name='Dia e hora do compromisso')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('description', models.TextField(blank=True, verbose_name='Informações do compromisso')),
            ],
        ),
    ]
