# Generated by Django 4.0.3 on 2024-07-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarmodel',
            old_name='psycologist',
            new_name='psychologist',
        ),
    ]
