# Generated by Django 4.0.3 on 2024-07-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_psycologist_calendarmodel_psychologist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Informações do compromisso'),
        ),
    ]
